language: node_js

node_js:
  - "10"

services: mongodb

before_script:
  - sleep 10
  - mongo sgat --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - npm run server &
  - npm run proxyApiGenerator
  - npm run iDB
  - npm test
