version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    container_name: serverSgat
    restart: on-failure
    depends_on:
      - mongo
    build: ./server
    ports:
      - "3001:3001"
    links:
      - mongo
  client:
    container_name: clientSgat
    restart: on-failure
    depends_on:
      - server
    build: ./client
    ports:
      - "3000:3000"
    links:
      - server